---

- name: EnsureMariaDBInstalled
  hosts: myhostslist
  remote_user: user
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: Install mariadb
      apt: name=mariadb-server update_cache=yes state=latest
