---

- name: EnsureTorInstalled
  hosts: myhostslist
  remote_user: user
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: Install Tor
      apt: name={{ item }} state=installed
      with_items:
        - tor
