---

- name: EnsurePHPBBInstalled
  hosts: myhostslist
  remote_user: user
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: Download PHPBB
      get_url:
        url: https://www.phpbb.com/files/release/phpBB-3.2.7.zip
        dest: /var/www/html/phpbb.zip
    - name: Remove index.html from apache
      shell: rm /var/www/html/index.html
    - name: Extract PHPBB
      unarchive:
        src: /var/www/html/phpbb.zip
        dest: /var/www/html
    - name: Move PHPBB to correct folder
      shell: mv /var/www/html/phpBB3/* /var/www/html
    - name: Remove phpbb.zip
      shell: rm /var/www/html/phpbb.zip
    - name: Set Permissions
      shell: chown -R www-data:www-data /var/www/html/ && chmod 660 /var/www/html/images/avatars/upload/ config.php && chmod 770 /var/www/html/store/ /var/www/html/cache/ /var/www/html/files/
      
#TODO create mysql user
#TODO initialize PHPBB

     - name: Remove PHPBB install-remnants
      shell: rm -r /var/www/html/install
