---

- name: EnsureDatabaseDBInstalled
  hosts: myhostslist
  remote_user: user
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: Install Database
      apt: name={{item}} update_cache=yes state=installed
      with_items:
        - mariadb-server
        - php-mysql
        
    - name: create mysql database
      mysql_db: name=my_database state=present
      
    - name: set mysql root password
      mysql_user:
        name=mysql_user
        priv="my_database.*:ALL"
        state=present
