---

- name: EnsurePHPInstalled
  hosts: myhostslist
  remote_user: user
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: Install php
      apt: name={{ item }} update_cache=yes state=latest
      with_items:
       - php7.3-cli
       - php7.3-common
       - php7.3-curl
       - php7.3-gd
       - php7.3-json
       - php7.3-mbstring
       - php7.3-xml
